### ISSUE TITLE
Getting System.NullReferenceException when try to use JieJie.Net.E

### ISSUE THREAD

**Issue by erensertkaya** [dcsoft-yyf/JIEJIE.NET#8]
This is what return on console, can anyone help ? 

System.NullReferenceException: Object reference not set to an instance of an object.
   at JIEJIE.DCJieJieNetEngine.EncryptEmbeddedResource(List`1 allMethod) in E:\Source\GitHub\JIEJIE.NET\source\JIEJIE.cs:line 7582
   at JIEJIE.DCJieJieNetEngine.HandleDocument() in E:\Source\GitHub\JIEJIE.NET\source\JIEJIE.cs:line 1862
   at JIEJIE.DCJieJieNetEngine.HandleDocument()
   at JIEJIE.ConsoleProgram.Main(String[] args) in E:\Source\GitHub\JIEJIE.NET\source\JIEJIE.cs:line 283

**Comment by dcsoft-yyf** [comment]
please send your assembly dll/exe file to me.



---Original---
From: "Eren ***@***.***&gt;
Date: Mon, Jun 6, 2022 22:16 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [dcsoft-yyf/JIEJIE.NET] Getting System.NullReferenceException whentry to use JieJie.Net.E (Issue #8)




 
This is what return on console, can anyone help ?
 
System.NullReferenceException: Object reference not set to an instance of an object.
 at JIEJIE.DCJieJieNetEngine.EncryptEmbeddedResource(List`1 allMethod) in E:\Source\GitHub\JIEJIE.NET\source\JIEJIE.cs:line 7582
 at JIEJIE.DCJieJieNetEngine.HandleDocument() in E:\Source\GitHub\JIEJIE.NET\source\JIEJIE.cs:line 1862
 at JIEJIE.DCJieJieNetEngine.HandleDocument()
 at JIEJIE.ConsoleProgram.Main(String[] args) in E:\Source\GitHub\JIEJIE.NET\source\JIEJIE.cs:line 283
